lkft-mainline-hikey960: update patch for the removal of arm_pm_restart
so that to workaround the following error:
/home/buildslave/srv/lkft/workspace/kernel/common/mainline/drivers/power/reset/hisi-reboot.c:111:2: error: use of undeclared identifier 'arm_pm_restart'
        arm_pm_restart = NULL;
        ^
1 error generated.

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
Change-Id: I7803f7824a4c1fea9826b002d93b2d3482375644