Revert "lkft-mainline-hikey960: remove patch for hikey960 i2s audio driver"
This reverts commit d0464441b3d5c5c20304e803587432d82edc2514.

Reason for revert:
ERROR: modpost: "snd_dmaengine_pcm_prepare_slave_config" [../../../hikey-modules/hikey960/android-mainline/sound/hi3660-i2s.ko] undefined!
ERROR: modpost: "devm_snd_dmaengine_pcm_register" [../../../hikey-modules/hikey960/android-mainline/sound/hi3660-i2s.ko] undefined!
make[3]: *** [/data/android/aosp/pure-master/lkft/kernel/common/mainline/scripts/Makefile.modpost:111：../../../hikey-modules/hikey960/android-mainline/Module.symvers] 错误 1
make[3]: *** 正在删除文件“../../../hikey-modules/hikey960/android-mainline/Module.symvers”
make[2]: *** [/data/android/aosp/pure-master/lkft/kernel/common/mainline/Makefile:1719：modules] 错误 2
make[2]: 离开目录“/data/android/aosp/pure-master/lkft/out/lkft-hikey960-aosp-master-mainline-gki/vendor-kernel/kernel/common/mainline”
make[1]: *** [Makefile:185：__sub-make] 错误 2
make[1]: 离开目录“/data/android/aosp/pure-master/lkft/kernel/common/mainline”
make: *** [Makefile:18：all] 错误 2
make: 离开目录“/data/android/aosp/pure-master/lkft/hikey-modules/hikey960/android-mainline”

Change-Id: Ifef2f34792fc6347f5778927a0e499f1b8c22f00